version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    networks:
      - iotnet

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lorawan_data
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - iotnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - iotnet

volumes:
  nodered_data:
  mysqldata:

networks:
  iotnet: